# Generated by Django 4.0.6 on 2023-08-01 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_category',
            fields=[
                ('bc_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tb_Book_category',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.TextField()),
                ('role', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_Login',
            },
        ),
        migrations.CreateModel(
            name='Member_register',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('contact_no', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('membership_id', models.CharField(blank=True, max_length=30, null=True)),
                ('membership_status', models.CharField(blank=True, max_length=20, null=True)),
                ('membership_validity', models.DateField(blank=True, null=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Library_App.login')),
            ],
            options={
                'db_table': 'tb_Member_register',
            },
        ),
        migrations.CreateModel(
            name='Book_details',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=80)),
                ('image', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=100)),
                ('publication_date', models.DateField()),
                ('no_of_pages', models.IntegerField()),
                ('no_of_copies', models.IntegerField()),
                ('description', models.TextField()),
                ('additional_data', models.TextField()),
                ('c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Library_App.book_category')),
            ],
            options={
                'db_table': 'tb_Book_details',
            },
        ),
    ]
