# Generated by Django 4.0.6 on 2023-08-01 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Library_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_details',
            old_name='publication_date',
            new_name='published_date',
        ),
    ]
