# Generated by Django 4.0.6 on 2023-08-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_App', '0003_remove_login_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_register',
            name='membership_taken_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member_register',
            name='membership_status',
            field=models.DateField(blank=True, null=True),
        ),
    ]
