# Generated by Django 3.2.7 on 2023-08-02 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Library_App', '0006_auto_20230802_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('subscription_type', models.CharField(max_length=50)),
                ('subscription_date', models.DateField()),
                ('subscription_validity', models.DateField()),
                ('amount', models.IntegerField()),
                ('m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Library_App.member_register')),
            ],
            options={
                'db_table': 'tb_Subscription',
            },
        ),
    ]
