# Generated by Django 4.0.6 on 2023-08-02 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Library_App', '0007_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowed_book',
            fields=[
                ('bd_id', models.AutoField(primary_key=True, serialize=False)),
                ('borrowed_date', models.DateField()),
                ('return_date', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Library_App.book_details')),
                ('m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Library_App.member_register')),
            ],
            options={
                'db_table': 'tb_Borrowed_book',
            },
        ),
        migrations.CreateModel(
            name='Book_reservation',
            fields=[
                ('br_id', models.AutoField(primary_key=True, serialize=False)),
                ('reserved_date', models.DateField()),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Library_App.book_details')),
                ('m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Library_App.member_register')),
            ],
            options={
                'db_table': 'tb_Book_reservation',
            },
        ),
    ]
