# Generated by Django 4.0.6 on 2023-08-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_App', '0008_borrowed_book_book_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowed_book',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
