# Generated by Django 4.0.6 on 2023-08-02 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Library_App', '0009_alter_borrowed_book_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_donation',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('contact_no', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('book_details', models.TextField()),
            ],
            options={
                'db_table': 'tb_Book_donation',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_date', models.DateField()),
                ('feedback', models.TextField()),
                ('reply', models.TextField(blank=True, null=True)),
                ('m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Library_App.member_register')),
            ],
            options={
                'db_table': 'tb_Feedback',
            },
        ),
    ]
