# Generated by Django 4.0.6 on 2023-08-03 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Library_App', '0011_book_reservation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dues',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('borrowed_date', models.DateField()),
                ('fine', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('bd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Library_App.borrowed_book')),
                ('m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Library_App.member_register')),
            ],
            options={
                'db_table': 'tb_Dues',
            },
        ),
    ]
