# Generated by Django 4.0.6 on 2023-08-03 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Library_App', '0012_dues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dues',
            name='borrowed_date',
        ),
    ]
