# Generated by Django 4.0.6 on 2023-08-03 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Library_App', '0013_remove_dues_borrowed_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dues',
            old_name='bd_id',
            new_name='bd',
        ),
    ]
