# Generated by Django 3.2.7 on 2023-08-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_App', '0014_rename_bd_id_dues_bd'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('n_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'tb_News',
            },
        ),
    ]
