# Generated by Django 3.2.7 on 2023-08-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_App', '0015_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
