# Generated by Django 3.2.7 on 2023-08-05 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Library_App', '0016_news_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_details',
            name='copies',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrowed_book',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrowed_book',
            name='borrowed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrowed_book',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
